GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER_READER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_USER_READER};

-- GRANT USAGE ON SCHEMA add TO ${DB_USER_READER};
-- GRANT SELECT ON ALL TABLES IN SCHEMA add TO ${DB_USER_READER};